### ISSUE TITLE
Nextra builds sporadically fail on Vercel

### ISSUE THREAD

**Issue by t3dotgg** [pingdotgg/uploadthing#16]
LOGS
```
[14:21:20.502] Running build in San Francisco, USA (West) – sfo1
[14:21:20.569] Cloning github.com/pingdotgg/uploadthing (Branch: theo/stream-fixes, Commit: c1f6068)
[14:21:21.394] Cloning completed: 824.266ms
[14:21:23.948] Restored build cache
[14:21:23.978] Running "vercel build"
[14:21:24.419] Vercel CLI 29.1.1
[14:21:24.740] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[14:21:24.744] Running "install" command: `pnpm install`...
[14:21:25.286] Scope: all 8 workspace projects
[14:21:25.535] ..                                       | Progress: resolved 1, reused 0, downloaded 0, added 0
[14:21:25.609] ..                                       |   +4   -4 +-
[14:21:26.595] ..                                       | Progress: resolved 4, reused 0, downloaded 4, added 4, done
[14:21:26.707] 
[14:21:26.709] Done in 1.9s
[14:21:26.725] Detected Next.js version: 13.4.1
[14:21:26.739] Running "turbo run build"
[14:21:27.034] • Packages in scope: docs
[14:21:27.034] • Running build in 1 packages
[14:21:27.034] • Remote caching enabled
[14:21:27.448] docs:build: cache miss, executing cb1ce34bb09d6835
[14:21:27.958] docs:build: 
[14:21:27.958] docs:build: > docs@ build /vercel/path0/docs
[14:21:27.958] docs:build: > next build
[14:21:27.958] docs:build: 
[14:21:28.513] docs:build: - info Linting and checking validity of types...
[14:21:30.288] docs:build: - info Creating an optimized production build...
[14:21:31.904] docs:build: [nextra] The repository is shallow cloned, so the latest modified time will not be presented. Set the VERCEL_DEEP_CLONE=true environment variable to enable deep cloning.
[14:21:40.627] docs:build: - info Compiled successfully
[14:21:40.636] docs:build: - info Collecting page data...
[14:21:41.008] docs:build: unhandledRejection Error: Cannot find module '../../next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/constants.js'
[14:21:41.008] docs:build: Require stack:
[14:21:41.008] docs:build: - /vercel/path0/docs/.next/server/pages/_document.js
[14:21:41.008] docs:build: - /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js
[14:21:41.009] docs:build: - /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
[14:21:41.009] docs:build: - /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js
[14:21:41.009] docs:build: - /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js
[14:21:41.009] docs:build: - /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
[14:21:41.009] docs:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
[14:21:41.010] docs:build:     at /vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:180:36
[14:21:41.010] docs:build:     at Module._load (node:internal/modules/cjs/loader:920:27)
[14:21:41.010] docs:build:     at Module.require (node:internal/modules/cjs/loader:1141:19)
[14:21:41.010] docs:build:     at require (node:internal/modules/cjs/helpers:110:18)
[14:21:41.010] docs:build:     at 4038 (/vercel/path0/docs/.next/server/pages/_document.js:895:18)
[14:21:41.010] docs:build:     at __webpack_require__ (/vercel/path0/docs/.next/server/webpack-runtime.js:25:43)
[14:21:41.013] docs:build:     at 3515 (/vercel/path0/docs/.next/server/pages/_document.js:43:20)
[14:21:41.014] docs:build:     at __webpack_require__ (/vercel/path0/docs/.next/server/webpack-runtime.js:25:43)
[14:21:41.015] docs:build:     at __webpack_exec__ (/vercel/path0/docs/.next/server/pages/_document.js:926:39) {
[14:21:41.015] docs:build:   type: 'Error',
[14:21:41.015] docs:build:   code: 'MODULE_NOT_FOUND',
[14:21:41.015] docs:build:   requireStack: [
[14:21:41.015] docs:build:     '/vercel/path0/docs/.next/server/pages/_document.js',
[14:21:41.015] docs:build:     '/vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require.js',
[14:21:41.016] docs:build:     '/vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js',
[14:21:41.016] docs:build:     '/vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js',
[14:21:41.016] docs:build:     '/vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/worker.js',
[14:21:41.025] docs:build:     '/vercel/path0/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
[14:21:41.025] docs:build:   ]
[14:21:41.026] docs:build: }
[14:21:41.061] docs:build:  ELIFECYCLE  Command failed with exit code 1.
[14:21:41.076] docs:build: ERROR: command finished with error: command (/vercel/path0/docs) pnpm run build exited (1)
[14:21:41.077] command (/vercel/path0/docs) pnpm run build exited (1)
[14:21:41.077] 
[14:21:41.077]   Tasks:    0 successful, 1 total
[14:21:41.077]  Cached:    0 cached, 1 total
[14:21:41.077]    Time:    14.301s 
[14:21:41.077] Summary:    /vercel/path0/.turbo/runs/2PcQ37IR7uGBm6Xx18ZdWpmvDiO.json
[14:21:41.077] 
[14:21:41.077]  ERROR  run failed: command  exited (1)
[14:21:41.091] Error: Command "turbo run build" exited with 1
[14:21:41.381] Deployment completed
[14:21:41.334] BUILD_UTILS_SPAWN_1: Command "turbo run build" exited with 1
```

**Comment by onbh943** [comment]
This seems to be the same issue, with solution. 

https://github.com/vercel/next.js/discussions/33364

**Comment by t3dotgg** [comment]
For history's sake, if anyone else has this issue this fixed it https://github.com/pingdotgg/uploadthing/pull/17/
