### ISSUE TITLE
[Bug]: Can't make UploadThing work as a function

### ISSUE THREAD

**Issue by theDanielJLewis** [pingdotgg/uploadthing#210]
### What happened?

I'm working in Next.js 13.4's app router where I want a file to upload via a function, _not_ from a user uploading something.

But build or upload processes keep giving me errors.

Here's my code.

uploadThing.ts:

```js
import { createUploadthing, type FileRouter } from "uploadthing/next";

const f = createUploadthing();
export const ourFileRouter = {
  voiceMessage: f(["audio", "video", "blob"]).onUploadComplete((data) =>
    console.log(data)
  ),
};

export type OurFileRouter = typeof ourFileRouter;

import { generateReactHelpers } from "@uploadthing/react/hooks";

export const { useUploadThing, uploadFiles } =
  generateReactHelpers<OurFileRouter>();
```

From the client component that triggers the upload:

```js
"use client";

// ...

async function onSend() {
    const file = new File([blob!], "audio", {
      lastModified: Date.now(),
      type: "audio/webm;codecs=opus",
    });
    await startUpload([file]);
}

// ...
```

On compilation, that gives me the following error:

```
- error node_modules/next/dist/build/webpack/loaders/next-flight-loader/module-proxy.js (153:22) @ Object.defineProperties.$$typeof.value
- error Error: Attempted to call generateReactHelpers() from the server but generateReactHelpers is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
    at Object.defineProperties.$$typeof.value (webpack-internal:///(sc_server)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/module-proxy.js:151:23)
    at eval (webpack-internal:///(sc_server)/./src/utils/uploadThing.ts:19:119)
    at (sc_server)/./src/utils/uploadThing.ts (MY_PROJECT/.next/server/app/api/uploadthing/route.js:552:1)
    at __webpack_require__ (MY_PROJECT/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./src/app/api/uploadthing/route.ts:7:76)
    at (sc_server)/./src/app/api/uploadthing/route.ts (MY_PROJECT/.next/server/app/api/uploadthing/route.js:542:1)
    at __webpack_require__ (MY_PROJECT/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fuploadthing%2Froute&page=%2Fapi%2Fuploadthing%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fuploadthing%2Froute.ts&appDir=%2MY_PROJECT%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2MY_PROJECT&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:15:175)
    at (sc_server)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fuploadthing%2Froute&page=%2Fapi%2Fuploadthing%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fuploadthing%2Froute.ts&appDir=%2MY_PROJECT%2Fsrc%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2MY_PROJECT&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (MY_PROJECT/.next/server/app/api/uploadthing/route.js:32:1)
    at __webpack_require__ (MY_PROJECT/.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (MY_PROJECT/.next/server/app/api/uploadthing/route.js:678:39)
    at MY_PROJECT/.next/server/app/api/uploadthing/route.js:679:28
    at Object.<anonymous> (MY_PROJECT/.next/server/app/api/uploadthing/route.js:682:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at requirePage (MY_PROJECT/node_modules/next/dist/server/require.js:156:12)
    at MY_PROJECT/node_modules/next/dist/server/load-components.js:71:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadComponentsImpl (MY_PROJECT/node_modules/next/dist/server/load-components.js:71:26)
    at async DevServer.findPageComponentsImpl (MY_PROJECT/node_modules/next/dist/server/next-server.js:772:36) {
  digest: undefined
}
```

So if I add `"use client"` to `uploadThing.ts`, I get `[UT] UploadThing dev server is now running!` on compilation. But then when I attempt to upload, I get this error:

```
- error Error: Cannot access .voiceMessage on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at Object.get (webpack-internal:///(sc_server)/./node_modules/next/dist/build/webpack/loaders/next-flight-loader/module-proxy.js:51:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/uploadthing/dist/next.mjs:215:34)
    at POST (webpack-internal:///(sc_server)/./node_modules/uploadthing/dist/next.mjs:326:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:249:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:111:36)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NoopTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:953:34)
    at ProxyTracer.startActiveSpan (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:993:36)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:107)
    at NoopContextManager.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:360:30)
    at ContextAPI.with (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/@opentelemetry/api/index.js:30:58)
    at NextTracerImpl.trace (webpack-internal:///(sc_server)/./node_modules/next/dist/server/lib/trace/tracer.js:100:32)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:237:53)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:42:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:191:97)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at Object.wrap (webpack-internal:///(sc_server)/./node_modules/next/dist/server/async-storage/request-async-storage-wrapper.js:77:24)
    at eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:190:75)
    at AsyncLocalStorage.run (node:async_hooks:338:14)
    at AppRouteRouteModule.execute (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:187:56)
    at AppRouteRouteModule.handle (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:310:41)
    at RouteHandlerManager.handle (/MY_PROJECT/node_modules/next/dist/server/future/route-handler-managers/route-handler-manager.js:24:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (/MY_PROJECT/node_modules/next/dist/server/base-server.js:1002:38)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/MY_PROJECT/node_modules/next/dist/server/base-server.js:1197:28)
    at async /MY_PROJECT/node_modules/next/dist/server/response-cache/index.js:99:36
```

### What did you expect to happen?

I expect it to just upload.

### Version

Next.js 13.4.8
UploadThing 5.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr0Bread** [comment]
I would recommend generating react helpers in the same file as your component(which should be using 'use client' directive)

**Comment by markflorkowski** [comment]
Either as @Mr0Bread mentioned, you should call generateReactHelpers() in the same file as your upload, or as the only thing in another file with a `use client;` directive.
