### ISSUE TITLE
[Bug]: utapi failing to upload blob

### ISSUE THREAD

**Issue by MarkLyck** [pingdotgg/uploadthing#321]
### What happened?

I'm trying to upload a file from a NextJS api route (app rotuer).

Here's my route.ts code:

```tsx
export async function POST(req: Request) {
  const file = await req.blob()
  // const filename = req.headers.get('x-vercel-filename') || 'file.txt'
  // const contentType = req.headers.get('content-type') || 'text/plain'
  // const fileType = `.${contentType.split('/')[1]}`

  const response = await utapi.uploadFiles(file)

  return NextResponse.json(response)
}
```

where req, is a file upload via `novel.sh` Editor.

This results in this error from uploadThing:

```
TypeError: Body is unusable
```
(see full error in relevant log output)

I have console logged `file` and it seems to print correctly as a Blob?

```
Blob {
  [Symbol(kHandle)]: Blob {  },
  [Symbol(kLength)]: 985828,
  [Symbol(kType)]: 'image/png'
}
```

I have managed to upload the same image I'm testing with, clientSide using the components. But I need this upload to work server-side.

I have also tried:

`const file = req.body` but that didn't work either.

### What did you expect to happen?

I would expect uploadThing to upload the file blob.

### Version

"uploadthing": "^5.5.2",
"@uploadthing/react": "^5.5.0",

### Reproduction Steps

- Create a nextjs@13 app with app router.
- Install novel npm package and render it in React.
- set up a route at /api/upload with the above code
- go to app and try to upload an image with the Editor.

### Link to reproduction

n/a

### Relevant log output

```bash
- error { source: 'edge-server', message: '' }
TypeError: Body is unusable
    at specConsumeBody (eval at requireWithFakeGlobalScope (/Users/marklyck/web/maker-pilot/node_modules/next/dist/compiled/edge-runtime/index.js:1:988485), <anonymous>:7059:15)
    at _Response.json (eval at requireWithFakeGlobalScope (/Users/marklyck/web/maker-pilot/node_modules/next/dist/compiled/edge-runtime/index.js:1:988485), <anonymous>:6960:18)
    at UploadThingError.fromResponse (webpack-internal:///(rsc)/./node_modules/@uploadthing/shared/dist/index.mjs:216:37)
    at uploadFilesInternal (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/server.mjs:52:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.uploadFiles (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/server.mjs:133:21)
    at async POST (webpack-internal:///(rsc)/./app/api/upload/route.ts:24:22)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:220:37)
- error unhandledRejection: Error [TypeError]: Body is unusable
    at specConsumeBody (eval at requireWithFakeGlobalScope (/Users/marklyck/web/maker-pilot/node_modules/next/dist/compiled/edge-runtime/index.js:1:988485), <anonymous>:7059:15)
    at _Response.json (eval at requireWithFakeGlobalScope (/Users/marklyck/web/maker-pilot/node_modules/next/dist/compiled/edge-runtime/index.js:1:988485), <anonymous>:6960:18)
    at UploadThingError.fromResponse (webpack-internal:///(rsc)/./node_modules/@uploadthing/shared/dist/index.mjs:216:37)
    at uploadFilesInternal (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/server.mjs:52:81)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.uploadFiles (webpack-internal:///(rsc)/./node_modules/uploadthing/dist/server.mjs:133:21)
    at async POST (webpack-internal:///(rsc)/./app/api/upload/route.ts:24:22)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:220:37) {
  digest: undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkLyck** [comment]
This does work using @vercel/blob

**Comment by Mr0Bread** [comment]
I'm not sure what req.blob returns, but can you set a name on a file? Like
```
file.name = 'some name'
```

We encountered similar issue

**Comment by juliusmarminge** [comment]
You need to set a filename on the blob:

```ts
export async function POST(req: Request) {
  const filename = req.headers.get('x-vercel-filename') || 'file.txt'
  const file = Object.assign(await req.blob(), { name: filename });
  const response = await utapi.uploadFiles(file)

  return NextResponse.json(response)
}
```
