### ISSUE TITLE
[bug]: NextJS build failed with SSRPlugin

### ISSUE THREAD

**Issue by omaSpencer** [pingdotgg/uploadthing#663]
### Provide environment information

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 105.69 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.1 - /opt/homebrew/bin/npm
    pnpm: 7.9.3 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - /opt/homebrew/bin/bun
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 122.1.63.165
    Chrome: 122.0.6261.94
    Safari: 17.2.1
  npmPackages:
    @uploadthing/react: ^6.3.2 => 6.3.2 
    typescript: 5.3.3 => 5.3.3 
    uploadthing: ^6.5.0 => 6.5.0
```

### Describe the bug

[19:29:33.894] Running "bun run build"
[19:29:33.995] $ next build
[19:29:35.033]    ▲ Next.js 14.1.1
[19:29:35.033] 
[19:29:35.095]    Creating an optimized production build ...
[19:30:25.069] Failed to compile.
[19:30:25.070] 
[19:30:25.071] node:module
[19:30:25.071] Module build failed: UnhandledSchemeError: Reading from "node:module" is not handled by plugins (Unhandled scheme).
[19:30:25.071] Webpack supports "data:" and "file:" URIs by default.
[19:30:25.071] You may need an additional plugin to handle "node:" URIs.
[19:30:25.071]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:399825
[19:30:25.073]     at Hook.eval [as callAsync] (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:28867), <anonymous>:6:1)
[19:30:25.073]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:13:26021)
[19:30:25.073]     at Object.processResource (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:399750)
[19:30:25.073]     at processResource (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:5308)
[19:30:25.074]     at iteratePitchingLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:4667)
[19:30:25.074]     at runLoaders (/vercel/path0/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js:1:8590)
[19:30:25.074]     at NormalModule._doBuild (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:399612)
[19:30:25.074]     at NormalModule.build (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:401640)
[19:30:25.075]     at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:28:82059
[19:30:25.075] 
[19:30:25.075] Import trace for requested module:
[19:30:25.075] node:module
[19:30:25.075] ./node_modules/uploadthing/server/index.js
[19:30:25.075] ./src/app/providers.tsx
[19:30:25.076] ./src/app/layout.tsx
[19:30:25.076] ./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fpage&page=%2Fpage&pagePath=private-next-app-dir%2Fpage.tsx&appDir=%2Fvercel%2Fpath0%2Fsrc%2Fapp&appPaths=%2Fpage&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!./src/app/page.tsx?__next_edge_ssr_entry__
[19:30:25.076] 
[19:30:25.080] 
[19:30:25.080] > Build failed because of webpack errors
[19:30:25.088] error: script "build" exited with code 1
[19:30:25.093] Error: Command "bun run build" exited with 1
[19:30:25.456] 

### Link to reproduction

https://stackblitz.com/github/pingdotgg/uploadthing/tree/main/examples/minimal-appdir?file=README.md

### To reproduce

// src/app/layout.tsx

import './globals.css'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'

import { Providers } from './providers'

const fontSans = FontSans({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

-------------------------------------------

// src/app/providers.tsx

import { type PropsWithChildren } from 'react'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'

import { ourFileRouter } from '@/app/api/uploadthing/core'

import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'

export function Providers({ children }: PropsWithChildren) {
  return (
    <ThemeProvider
      attribute='class'
      defaultTheme='system'
      enableSystem
      disableTransitionOnChange
    >
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      {children}
      <Toaster />
    </ThemeProvider>
  )
}

### Additional information

In dev mode works fine.

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juliusmarminge** [comment]
i believe this is due to edge runtimes. this is already fixed in https://github.com/pingdotgg/uploadthing/pull/627 and will be part of the next update.

you should be able to disable edge runtime for now until that release is out though, or use this canary version: `uploadthing@6.5.1-canary.1bafd62`
