### ISSUE TITLE
[bug]:UploadThingError     at INTERNAL_DO_NOT_USE__fatalClientError

### ISSUE THREAD

**Issue by abela2112** [pingdotgg/uploadthing#902]
### Provide environment information

```bash
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 3.31 GB / 15.88 GB
  Binaries:
    Node: 20.11.1 - C:\node-v20.11.1-win-x64\node.EXE
    npm: 10.2.4 - C:\node-v20.11.1-win-x64\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @uploadthing/react: ^6.7.2 => 6.7.2
    typescript: 5.5.2 => 5.5.2
    uploadthing: ^6.13.2 => 6.13.2
```

### Describe the bug

I can see file in uploadthing files dashboard but onUploadError throw below error.
Code -
```
<UploadDropzone
      endpoint={endpoint}
      onClientUploadComplete={(res) => {
        onChange(res?.[0].url);
      }}
      onUploadError={(error) => {
        console.error("Upload Error", error);
        console.log("error.message", error.stack);
        toast.error(`${error?.message}`);
      }}
    ></UploadDropzone>
```
and found this error

```
app-index.tsx:25 
 Upload Error 
UploadThingError
    at INTERNAL_DO_NOT_USE__fatalClientError (index.js:352:1)
    at eval (button-client-D2-JDNio.js:196:66)
Caused by: RetryError
    at eval (index.js:297:166)
    at eval (Micro.js:1137:46)
    at eval (Micro.js:885:1)
    at eval (Micro.js:497:1)
    at Object.execute (Micro.js:472:1)
    at eval (Micro.js:885:1)
    at eval (Micro.js:1272:1)
    at eval (Micro.js:1463:1)
    at eval (Micro.js:852:1)
    at eval (Micro.js:497:1)
    at Object.execute (Micro.js:472:1)
    at eval (Micro.js:885:1)
    at eval (Micro.js:497:1)
    at Object.execute (Micro.js:472:1)
    at resume (Micro.js:673:1)
    at eval (Micro.js:731:1)
﻿

```

### Link to reproduction

https://docs.uploadthing.com/getting-started/appdir

### To reproduce

I followed the instructions [https://docs.uploadthing.com/getting-started/appdir](url)

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jameshenry2020** [comment]
i am having same issue, i am using uploadthing with nextjs any solution please

**Comment by mrcoded** [comment]
i hope this gets resolved soon, it is breaking my nextjs app too
