### ISSUE TITLE
[bug]: UploadThingError: Failed to parse response from UploadThing server

### ISSUE THREAD

**Issue by EmraanKhalid** [pingdotgg/uploadthing#932]
### Provide environment information

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 AMD Ryzen 3 PRO 3300U w/ Radeon Vega Mobile Gfx
    Memory: 2.93 GB / 13.93 GB
  Binaries:
    Node: 22.5.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @uploadthing/react: ^6.0.2 => 6.7.2
    typescript: ^5 => 5.5.4
    uploadthing: ^6.1.0 => 6.13.2
```

### Describe the bug

I have tried everything but the issue persists. When every i am uploading a image file using UploadDropzone after it when ever i press the upload button it throws me error  "UploadThingError: Failed to parse response from UploadThing server". is anyone able to help me out on this?

### Link to reproduction

https://github.com/EmraanKhalid/plura.git

### To reproduce

```
"use client"
import { FileIcon, X } from 'lucide-react'
import Image from 'next/image'
import React from 'react'
import { Button } from '../ui/button'
import { UploadDropzone } from '@/lib/uploadthing'

type Props = {
  apiEndpoint: 'agencyLogo' | 'avatar' | 'subaccountLogo'
  onChange: (url?: string) => void
  value?: string
}

const FileUpload = ({ apiEndpoint, onChange, value }: Props) => {
  const type = value?.split('.').pop()

  if (value) {
    return (
      <div className="flex flex-col justify-center items-center">
        {type !== 'pdf' ? (
          <div className="relative w-40 h-40">
            <Image
              src={value}
              alt="uploaded image"
              className="object-contain"
              fill
            />
          </div>
        ) : (
          <div className="relative flex items-center p-2 mt-2 rounded-md bg-background/10">
            <FileIcon />
            <a
              href={value}
              target="_blank"
              rel="noopener noreferrer"
              className="ml-2 text-sm text-indigo-500 dark:text-indigo-400 hover:underline"
            >
              View PDF
            </a>
          </div>
        )}
        <Button
          onClick={() => onChange('')}
          variant="ghost"
          type="button"
        >
          <X className="h-4 w-4" />
          Remove Logo
        </Button>
      </div>
    )
  }
  return (
    
    <div className="w-full bg-muted/30">
      
      <UploadDropzone
        endpoint={apiEndpoint}
        onClientUploadComplete={(res) => {
          console.log(res)
          onChange(res?.[0].url)
          
        }}
        onUploadError={(error: Error) => {
          console.log(error)
        }}
      />
    </div>
  )
}

export default FileUpload
```

### Additional information

```
UploadThingError: Failed to parse response from UploadThing server
    at eval (index.js:196:141)
    at eval (Micro.js:1493:189)
    at eval (Micro.js:1432:5)
    at eval (Micro.js:1430:14)
    at eval (Micro.js:1430:14)
    at eval (Micro.js:1010:5)
    at eval (Micro.js:1621:7)
    at eval (Micro.js:1010:5)
    at eval (Micro.js:1041:14)
    at eval (Micro.js:679:3)
    at Object.execute (Micro.js:654:7)
    at resume (Micro.js:847:22)
    at eval (Micro.js:889:60)Caused by: InvalidJson
    at Object.catch (webpack-internal:///(app-pages-browser)/./node_modules/@uploadthing/shared/dist/index.js:462:25)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/effect/dist/esm/Micro.js:889:85)
```

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR fixing this bug!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by markflorkowski** [comment]
Your repro link is either private or actually empty. The code you have in the issue *looks* fine as far as I can tell, can you aslo share your server code (fileRouter)?

**Comment by EmraanKhalid** [comment]
Sorry my apologies you can check it now. And thanks for helping me out.

**Comment by EmraanKhalid** [comment]
Sorry my apologies you can check it now. And thanks for helping me out.

**Comment by markflorkowski** [comment]
![image](https://github.com/user-attachments/assets/4d3c5d7e-a582-4e15-86a6-e58a54b7e088)

I don't think it would cause the error you saw (I would expect nothing to work at all) but your `route.ts` filename has a typo.

**Comment by EmraanKhalid** [comment]
Thanks alot brother haven't noticed it and it is the bug which is causing
this issue thanks alot for your guidance.

**Comment by Ayewealth** [comment]
I am still have the issue

even as my filename is correct

**Comment by Nusab19** [comment]
@Ayewealth Any updates?

I'm facing the same issue. My filenames are all correct

**Comment by mathysIN** [comment]
Same issue here. My project was working correctly 1 month ago
